DANGER_HEADERS = [
    "x-arastta", "Servlet-engine", "sw-language-id", "x-kinsta-cache", "expect-ct", "x-cdn", "X-Pardot-LB", "x-sucuri-id", "X-Varnish-Hostname", "Chec-Version", "x-cloud-trace-context", "x-oss-object-type", "x-0-version", "X-Powered-By", "X-Elcodi", "X-Drupal-Cache", "MicrosoftSharePointTeamServices", "tb-cache-country", "X-Jive-Flow-Id", "X-Azure-Ref", "X-EdgeConnect-Origin-MEX-Latency", "X-Rocket-Nginx-Bypass", "x-sdp-app-type", "X-Akaunting", "x-lw-cache", "solodev_session", "x-ipfs-pop", "X-Generator", "X-SharePointHealthScore", "X-Flowproxy-Author", "x-servername", "x-shopify-stage", "azure-slotname", "X-Pingback", "x-hs-hub-id", "X-NF-Request-ID", "platform", "X-GoCache-CacheStatus", "COMMERCE-SERVER-SOFTWARE", "X-Shopery", "X-EdgeConnect-MidMile-RTT", "x-turbo-charged-by", "sw-version-id", "X-StatusPage-Skip-Logging", "X-Starhost", "x-ipfs-lb-pop", "X-Pardot-Route", "X-PHPFusion", "Liferay-Portal", "x-0-t", "x-amz-id-2", "X-Streams-Distribution", "Powered-By", "X-Includable-Version", "X-Powered-By-Plesk", "X-WPE-Loopback-Upstream-Addr", "X-Plenty-Shop", "x-amz-version-id", "X-Built-With", "X-Backside-Transport", "x-elasticpress-query", "x-distributor", "X-Server-Powered-By", "X-Dotclear-Static-Cache", "x-ipfs-gateway-host", "x-ipfs-roots", "X-Powered-Framework", "X-epages-RequestId", "content-disposition", "x-tncms", "X-Foswikiaction", "replit-cluster", "Via", "x-zendesk-user-id", "X-Firefox-Http3", "X-DataDome", "kbn-version", "X-Protected-By", "x-ms-client-request-id", "cms-version", "X-CDN-Forward", "x-goog-storage-class", "X-Mod-Pagespeed", "sw-invalidation-states", "X-Unbounce-PageId", "x-azoya-webisteid", "x-canvas-meta", "Derak-Umbrage", "X-Umbraco-Version", "wpe-backend", "X-Drectory-Script", "X-Jimdo-Wid", "X-Wix-Server-Artifact-Id", "X-B3-TraceId", "WWW-Authenticate", "X-Fastcgi-Cache", "X-Wix-Request-Id", "x-ipfs-root", "x-oracle-dms-ecid", "X-B3-Sampled", "x-styx-req-id", "X-B3-SpanId", "X-GitHub-Request-Id", "x-yandex-captcha", "via", "x-fw-serve", "x-pantheon-styx-hostname", "X-Varnish-Action", "X-Jive-Request-Id", "x-fw-server", "x-orckestra-commerce", "x-platform-cluster", "X-Advertising-By", "X-Application-Context", "Server", "author", "X-OWA-Version", "X-Amz-Cf-Id", "X-ATG-Version", "X-CF2", "x-trove-country-code", "powered-by", "section-io-id", "x-vercel-cache", "SPRequestGuid", "X-Page-Speed", "X-Iinfo", "x-ipfs-root-cid", "section-io-origin-time-seconds", "sw-context-token", "X-Wix-Renderer-Server", "x-endurance-cache-level", "server", "x-generator", "X-Akamai-Transformed", "x-via-fastly:", "content-security-policy-report-only", "x-bubble-perf", "Weglot-Translated", "SharePointHealthScore", "X-Generated-By", "WP-Super-Cache", "X-B3-ParentSpanId", "x-bubble-capacity-used", "Alt-Svc", "x-replicache-requestid", "Arastta", "X-Fastly-Request-ID", "X-Confluence-Request-Time", "x-fastly-origin", "Fastly-Debug-Digest", "x-amz-err-message", "X-CDN", "x-clockwork-version", "X-EC-Debug", "CMS-Version", "X-JSL", "x-shopid", "X-Varnish-Age", "fly-request-id", "X-Ensi-Platform", "X-KoobooCMS-Version", "IBM-Web2-Location", "X-Foswikiuri", "X-JIVE-USER-ID", "X-LAGOON", "report-to", "x-statsig-region", "azure-regionname", "Cookie", "x-fw-hash", "x-served-by", "powered", "x-yerdle-app-name", "WebDevSrc", "X-Powered-PublicCMS", "X-VARITI-CCR", "X-Pass-Why", "X-Content-Encoded-By", "X-Flow-Powered", "x-now-trace", "X-XRDS-Location", "x-vercel-id", "x-contentful-request-id", "azure-version", "x-platform-server", "x-amz-rid", "x-fw-type", "x-cf-ipfs-cache-status", "X-ServedBy", "X-Lift-Version", "x-rebelmouse-surrogate-control", "x-sanity-shard", "x-provided-by", "X-Cache", "x-trove-order-uuid", "X-Pardot-Rsp", "cms-name", "X-Firefox-Spdy", "ch-powered-by", "x-backend-server", "X-Arastta", "x-powered-by", "azure-sitename", "x-render-origin-server", "X-Jenkins", "DNNOutputCache", "x-platform-processor", "x-oss-request-id", "X-Supplied-By", "X-Ghost-Cache-Status", "kbn-name", "X-Varnish-Cache", "X-CF1", "x-ipfs-datasize", "X-Tumblr-User", "cf-ray", "X-Compressed-By", "x-envoy-upstream-service-time", "x-lagoon", "X-Global-Transaction-ID", "x-sucuri-cache:", "X-Varnish", "x-fastly-request-id", "x-amz-err-code", "X-Backdrop-Cache", "Composed-By", "content-security-policy", "x-ms-correlation-request-id", "X-Flex-Lang", "x-0-status", "X-StatusPage-Version", "x-fw-static", "X-AspNet-Version", "x-hostname", "X-Inertia", "x-redirected-by", "frontastic-request-id", "x-litespeed-cache", "x-amz-request-id", "X-MCF-ID", "x-cluster", "x-jive-chrome-wrapped", "x-amzn-waf-action", "x-ventryshield-cache-status", "cf-cache-status", "cache-provider", "x-platform-router", "x-auth0-requestid", "X-Powered-CMS", "section-io-origin-status", "Smug-CDN", "tb-cache-group", "X-AH-Environment", "x-amz-delete-marker", "x-ms-gateway-requestid", "x-ipfs-path", "x-ventryshield-sid", "X-Hosting-Provider", "x-rebelmouse-cache-control", "X-Rack-Cache", "x-bubble-capacity-limit", "x-engine", "X-B3-Flags", "x-oss-storage-class", "x-amz-req-time-micros", "X-Jimdo-Instance", "X-Spip-Cache", "X-DataDome-CID", "OracleCommerceCloud-Version", "host-header", "x-nestify-cache", "x-trove-app-name", "Itx-Generated-Timestamp"
]

DANGER_USER_AGENTS = [
    # get from https://github.com/fastly/waf_testbed/blob/master/templates/default/scanners-user-agents.data.erb with adaptation
    "gobuster/", "curl/", "(hydra)", ".nasl", "absinthe", "advanced email extractor", "arachni/", "autogetcontent", "bilbo", "bfac", "brutus", "brutus/aet", "bsqlbf", "cgichk", "cisco-torch", "commix", "core-project/1.0", "crimscanner/", "datacha0s", "dirbuster", "domino hunter", "dotdotpwn", "email extractor", "fhscan core 1.", "floodgate", "get-minimal", "gootkit auto-rooter scanner", "grabber", "grendel-scan", "havij", "inspath", "internet ninja", "jaascois", "zmeu", "masscan", "metis", "morfeus fucking scanner", "mysqloit", "n-stealth", "nessus", "netsparker", "nikto", "nmap nse", "nmap scripting engine", "nmap-nse", "nsauditor", "openvas", "pangolin", "paros", "pmafind", "prog.customcrawler", "qualyswas", "s.t.a.l.k.e.r.", "security scan", "springenwerk", "sql power injector", "sqlmap/", "sqlninja", "teh forest lobster", "this is an exploit", "toata dragostea", "toata dragostea mea pentru diavola", "uil2pn", "user-agent:", "vega/", "voideye", "w3af.sf.net", "w3af.sourceforge.net", "w3af.org", "webbandit", "webinspect", "webshag", "webtrends security analyzer", "webvulnscan", "whatweb", "whcc/", "wordpress hash grabber", "xmlrpc exploit", "wpscan", 
    # get from https://github.com/fastly/waf_testbed/blob/master/templates/default/scripting-user-agents.data.erb with adaptation
    "dav.pm/v", "libwww-perl", "python-httplib2", "python-requests", "python-urllib", "typhoeus", "winhttp.winhttprequest", 
    # does these ua not in valid user?
    "mozilla/4.0 (compatible)", "mozilla/4.0 (compatible; msie 6.0; win32)", "mozilla/5.0 sf/", "mozilla/5.0 sf//", 
    # get from https://github.com/fastly/waf_testbed/blob/master/templates/default/crawlers-user-agents.data.erb with adaptation
    "black widow", "blackwidow", "prowebwalker", "pymills-spider/", "ahrefsbot", "piplbot", "grapeshotcrawler/2.0", "grapefx", "searchmetricsbot", "rogerbot", "mj12bot", "owlin bot", "lingewoud-550-spyder"
]

HTML_CONTENT_TYPES = [
  "text/html", "application/html"
]

JAVASCRIPT_CONTENT_TYPES = [
  "text/javascript", "application/javascript", "text/x-javascript", "text/x-js", "text/ecmascript" 
]

CSS_CONTENT_TYPES = [
  "text/css, application/css, application/x-css, text/x-css"
]

XML_CONTENT_TYPES = [
  "application/xml", "text/xml"
]

HTTP_STATUS_CODES = [
    401, 403, 404, 500
]

DANGER_COOKIE = ["BITRIX_SM_SALE_UID","_redmine_session","lm_online","nette-browser","sid_key","dwsid","bownow_act","_ga_*","botble_session","voracio_sessionid","bynder","Dynamicweb","ASPSESSION","ASLBSACORS","F5_ST","qtype-session","wgSession","_sp_enable_dfp_personalized_ads","INVENIOSESSION","kameleoonVisitorCode","_gat","i_like_gogits","vscommerce","ku1-vid","optimizelyEndUserId","sensorsdata2015session","SAKAIID","CMSSESSID","sails.sid","OJSSID","phpbb","com.salesforce","grwng_uid","exp_last_activity","usces_cookie","MRHSession","mage-translation-file-version","droxit_a11y_state","ZES_BACKEND","_absorb_ui_session","__stripe_mid","i_like_gitea","websale_ac","_boss_session","_gat_congressus_analytics","SimpleSAML","foodomaa_session","OCSESSID","CMSCookieLevel","PUBLICCMS_USER","PrestaShop","huberway_session","adonis-session-values","layer0_destination","_px3","trbo_session","bownow_cid","OpenGrok","mybb[lastvisit]","_gphw_mode","_help_center_session","_pxvid","mage-cache-storage","YII_CSRF_TOKEN","DokuWiki","sp","Demdex","F5_HT_shrinked","VivvoSessionId","__stripe_sid","EPiServer","rrpvid","EPiTrace","STUID","ometria","bf_session","4TellCart","swell-session","mybb[lastactive]","__Host-next-auth.csrf-token","MOODLEID_","gr_user_id","_gocertify_session","GlobalE_SupportThirdPartCookies","_chorus_geoip_continent","alumniq-online-giving","ekmpowershop","X-Magento-Vary","JTLSHOP","MRHSHint","spp_orderform","ASLBSA","trbo_usr","ELOQUA","_gumroad_app_session","_june_session","bblastvisit","TiPMix","3dvisit","SMARTSTORE.CUSTOMER","CraftSessionId","bsmartstate","__cfduid","MoodleSession","congressus_session","TIN","exp_csrf_token","Aws.customer","4TellSession","bfx.logLevel","_gumroad_guid","phoenix_p_session","mage-cache-storage-section-invalidation","ICMSSession","ahoy_track","Bugzilla_login_request_cookie","soteshop","PLAY_SESSION","__derak_user","TotaraSession","_hybris","shoplazza_source","SC_ANALYTICS_GLOBAL_COOKIE","bfx.language","_simplero_session_id","cloudify_session","CONCRETE5","TWIKISID","REVEL_FLASH","_gat_teachableTracker","LastMRH_Session","ahoy_visitor","ASP.NET_SessionId","SimpleSAMLSessionID","statjoy_metrics","bownow_aid","exp_tracker","_session_id","mage-translation-storage","bbsessionhash","blesta_sid","cprelogin","bigWAdminID","Loop54User","VtexStoreVersion","beyable-cart","_zendesk_cookie","_dy_ses_load_seq","X-DR-SHOPPER-ets","bookstack_session","graffitibot","AWSELB","__utma","PIWIK_SESSID","typof_session","ZM_TEST","memberstack","STVID","sf_redirect","voracio_csrf_token","sxa_site","ci_csrf_token","bfx.country:","OSTSESSID","AWSALBCORS","ahoy_visit","k_visit","ku1-sid","bfx.apiKey:","_duelcsrf","__cf_bm","_thinkific_session","pll_language","pterodactyl_session","_kjb_session","MRHSequence","layer0_bucket","cs_secure_session","_mp_permissions","_shopify_s","_uetvid","spp_csrf","django_language","_dy_geo","ipbWWLsession_id","frontend","rr-testCookie","REVLIFTER","bm_sv","promobuilding_session","_bsalemarket_session","MAKACSESSION","phsid","thinkphp_show_page_trace","datadome-_zldt","eZSESSID","october_session","_fly","h2o_casper","plug_pay_session","EPiSessionId","SmartFocus","VtexWorkspace","shopaholic_cart_id","ak_bmsc","GlobalE_CT_Data","beyable-cartd","ARRAffinity","jibres","Domain","F5_fullWT","pinoox_session","sailthru_pageviews","pyrocms","_ga","akaas_AB-Testing","rawabit_session","sc_expview","BITRIX_SM_LAST_IP","cakephp","chorus_preferences","SFOSWIKISID","_pxff_cc","laravel_session","wp-wpml_current_language","TNEW","__derak_auth","sensorsdata2015jssdkcross","apptus.sessionKey","_gauges_","SMARTSTORE.VISITOR","snipcart-cart","iexexchanger_session","BAGawin","InstantCMS[logdate]","paymenter_session","4Tell","inveonSessionId","NS_VER","eGold","__Host-nc_sameSiteCookiestrict","Popmenu-Token","tallentor_widget","_ALGOLIA","EPi:StateMarker","dw_dnt","FESESSIONID","SiteVisionLTM","vtex_session","bigwareCsid","bm_sz","FLOWPROXY-ORIGIN","OptanonConsent","CMSPreferredCulture","_wmuid","layer0_eid","JSESSIONID","_zendesk_shared_session","_gitlab_session","rc2c-erotica","_solusquare","ci_session","_aw_xid","adonis-session","ushahidi","Nop.customer","Grand.customer","_mshops_ga_gid","ZENDSERVERSESSID","koken_referrer","VtexFingerPrint","rakuten-source","_sp_id","SPIRITSHOP_ID","popup_shopGold","cpsession","_podia_storefront_visitor_id","PHPSESSID","xf_csrf","LithiumVisitor","_gat_wnd_header","xf_session","flyspray_project","X-DR-THEME","aam_uuid","ARK_ID","hotaru_mobile","dps_site_id","SC_OS_SessionId","ventryshield_pre","_mastodon_session","_shopify_y","omnisendSessionID","popup_shopGold_time","osCsid","bownow_mbid","INV.Customer","cratejoy_muffin42","datadome","REVEL_SESSION","datadome-_zldp","spp_session","DSSIGNIN","_qta_rum","apptus.customerKey","__Secure-next-auth.callback-url","zid_catalog_session","bblastactivity","TawkConnectionTime","BITRIX_SM_GUEST_ID","GlobalE_Data","ipbWWLmodpids","dtCookie1","MOIN_SESSION","coconut_calendar","ppwp_wp_session","mediavine_session","kohanasession","ImpressCMS","DotNetNukeAnonymous","FOSWIKISTRIKEONE","_pxhd"," __Host-nc_sameSiteCookielax","e107_tz","forterToken","AWSALB","_uetsid"]

DANGER_HEADERS_PAIR = {
    "x-arastta": "Arastta/2.0.3",
    "Servlet-engine": "Tomcat/9.0.41",
    "sw-language-id": "en-US",
    "x-kinsta-cache": "Hit",
    "expect-ct": "enforce, max-age=86400",
    "x-cdn": "CloudFront",
    "X-Pardot-LB": "LB-12345",
    "x-sucuri-id": "SUCURI-WEB-SECURITY",
    "X-Varnish-Hostname": "varnish-server-1",
    "Chec-Version": "3.2.1",
    "x-cloud-trace-context": "projects/123456/traces/7890abcd",
    "x-oss-object-type": "image/jpeg",
    "x-0-version": "2.7.1",
    "X-Powered-By": "Express/4.17.1",
    "X-Elcodi": "v1.0.0",
    "X-Drupal-Cache": "HIT",
    "MicrosoftSharePointTeamServices": "15.0.0.1234",
    "tb-cache-country": "US",
    "X-Jive-Flow-Id": "abcdefgh12345678",
    "X-Azure-Ref": "abcdefg-1234-5678-90ab-cdef12345678",
    "X-EdgeConnect-Origin-MEX-Latency": "10ms",
    "X-Rocket-Nginx-Bypass": "yes",
    "x-sdp-app-type": "web",
    "X-Akaunting": "v2.0.0",
    "x-lw-cache": "HIT",
    "solodev_session": "d41d8cd98f00b204e9800998ecf8427e",
    "x-ipfs-pop": "us-west",
    "X-Generator": "WordPress/5.7.2",
    "X-SharePointHealthScore": "0",
    "X-Flowproxy-Author": "admin",
    "x-servername": "webserver-123",
    "x-shopify-stage": "production",
    "azure-slotname": "staging",
    "X-Pingback": "https://example.com/xmlrpc.php",
    "x-hs-hub-id": "12345",
    "X-NF-Request-ID": "abcdef1234567890",
    "platform": "Java/11.0.2",
    "X-GoCache-CacheStatus": "HIT",
    "COMMERCE-SERVER-SOFTWARE": "Magento/2.4.2",
    "X-Shopery": "shopery/3.1.0",
    "X-EdgeConnect-MidMile-RTT": "50ms",
    "x-turbo-charged-by": "WP Rocket",
    "sw-version-id": "v3.2.1",
    "X-StatusPage-Skip-Logging": "true",
    "X-Starhost": "StarHost Web Server",
    "x-ipfs-lb-pop": "us-east",
    "X-Pardot-Route": "/home",
    "X-PHPFusion": "v9.03.00",
    "Liferay-Portal": "Liferay DXP/7.3",
    "x-0-t": "abcdefgh12345678",
    "x-amz-id-2": "abcdefg-1234-5678-90ab-cdef12345678",
    "X-Streams-Distribution": "CDN",
    "Powered-By": "PHP/7.4.10",
    "X-Includable-Version": "1.2.3",
    "X-Powered-By-Plesk": "PHP/7.4.21",
    "X-WPE-Loopback-Upstream-Addr": "127.0.0.1",
    "X-Plenty-Shop": "E-commerce Platform",
    "x-amz-version-id": "987654321",
    "X-Built-With": "Python 3.9.6",
    "X-Backside-Transport": "OK",
    "x-elasticpress-query": "GET /search?q=example",
    "x-distributor": "Acme Distributors",
    "X-Server-Powered-By": "Nginx",
    "X-Dotclear-Static-Cache": "Hit",
    "x-ipfs-gateway-host": "gateway.ipfs.io",
    "x-ipfs-roots": "QmXaBhUf1iaPdjo",
    "X-Powered-Framework": "Django/3.2.3",
    "X-epages-RequestId": "efgh1234",
    "content-disposition": "attachment; filename=\"example.pdf\"",
    "x-tncms": "True",
    "X-Foswikiaction": "view",
    "replit-cluster": "us-central1",
    "Via": "1.1 proxy.example.com",
    "x-zendesk-user-id": "12345",
    "X-Firefox-Http3": "h3-27",
    "X-DataDome": "shielded",
    "kbn-version": "7.12.0",
    "X-Protected-By": "Ninja Firewall",
    "x-ms-client-request-id": "67890abcdefg",
    "cms-version": "WordPress/5.7.2",
    "X-CDN-Forward": "AWS CloudFront",
    "x-goog-storage-class": "STANDARD",
    "X-Mod-Pagespeed": "1.13.35.2-0",
    "sw-invalidation-states": "2",
    "X-Unbounce-PageId": "12345",
    "x-azoya-webisteid": "abcdefg12345",
    "x-canvas-meta": "width=1024, height=768",
    "Derak-Umbrage": "true",
    "X-Umbraco-Version": "8.11.1",
    "wpe-backend": "wordpress",
    "X-Drectory-Script": "WordPress/5.7.2",
    "X-Jimdo-Wid": "w12345678",
    "X-Wix-Server-Artifact-Id": "wix-server-123",
    "X-B3-TraceId": "abcdef1234567890",
    "WWW-Authenticate": "Basic realm=\"Example\"",
    "X-Fastcgi-Cache": "HIT",
    "X-Wix-Request-Id": "12345",
    "x-ipfs-root": "Qmbcdefgh1234567890abcdefg",
    "x-oracle-dms-ecid": "abcdefg-1234-5678-90ab-cdef12345678",
    "X-B3-Sampled": "1",
    "x-styx-req-id": "abcdefg12345",
    "X-B3-SpanId": "bcdefg12345",
    "X-GitHub-Request-Id": "abcdefg12345",
    "x-yandex-captcha": "abcdefg12345",
    "via": "1.1 proxy.example.com",
    "x-fw-serve": "AkamaiGHost",
    "x-pantheon-styx-hostname": "styxabcdefg",
    "X-Varnish-Action": "HIT",
    "X-Jive-Request-Id": "12345",
    "x-fw-server": "AkamaiGHost",
    "x-orckestra-commerce": "Orckestra C1",
    "x-platform-cluster": "aws",
    "X-Advertising-By": "Google AdSense",
    "X-Application-Context": "application",
    "Server": "Apache/2.4.46",
    "author": "John Doe",
    "X-OWA-Version": "15.0.0.1234",
    "X-Amz-Cf-Id": "12345abcdefg",
    "X-ATG-Version": "10.2",
    "X-CF2": "abcdefg1234567890",
    "x-trove-country-code": "US",
    "powered-by": "Express",
    "section-io-id": "12345",
    "x-vercel-cache": "HIT",
    "SPRequestGuid": "abcdef1234567890",
    "X-Page-Speed": "1.13.35.2-0",
    "X-Iinfo": "1-1234567-0 0CNN RT(12345678 1234567890 12345) q(0 -1 -1 -1) r(1 -1)",
    "x-ipfs-root-cid": "Qmbcdefgh1234567890abcdefg",
    "section-io-origin-time-seconds": "0.123",
    "sw-context-token": "1234567890abcdefg",
    "X-Wix-Renderer-Server": "renderer.wix.com",
    "x-endurance-cache-level": "HIT",
    "server": "nginx/1.21.1",
    "x-generator": "WordPress/5.7.2",
    "X-Akamai-Transformed": "9 12345 0 pmb=mTOE,2mRUM,3",
    "x-via-fastly:": "fastly.net",
    "content-security-policy-report-only": "default-src 'self'",
    "x-bubble-perf": "12345abcdef",
    "Weglot-Translated": "true",
    "SharePointHealthScore": "0",
    "X-Generated-By": "Weglot",
    "WP-Super-Cache": "1.7.3",
    "X-B3-ParentSpanId": "cdefg12345",
    "x-bubble-capacity-used": "100",
    "Alt-Svc": "h3-27=\":443\"; ma=12345",
    "x-replicache-requestid": "12345abcdefg",
    "Arastta": "1.6.2",
    "X-Fastly-Request-ID": "12345abcdefg",
    "X-Confluence-Request-Time": "12345",
    "x-fastly-origin": "example.com",
    "Fastly-Debug-Digest": "abcdefg12345",
    "x-amz-err-message": "ResourceNotFoundException",
    "X-CDN": "Incapsula",
    "x-clockwork-version": "2.0",
    "X-EC-Debug": "abcd1234",
    "CMS-Version": "Joomla/4.0.0",
    "X-JSL": "v2.0",
    "x-shopid": "abcdefg",
    "X-Varnish-Age": "12345",
    "fly-request-id": "12345abcdefg",
    "X-Ensi-Platform": "custom",
    "X-KoobooCMS-Version": "1.0.0",
    "IBM-Web2-Location": "abcdefg",
    "X-Foswikiuri": "https://example.com",
    "X-JIVE-USER-ID": "abcdef1234567890",
    "X-LAGOON": "Lagoon",
    "report-to": "default",
    "x-statsig-region": "us-east-1",
    "azure-regionname": "East US",
    "Cookie": "session=abcdef1234567890",
    "x-fw-hash": "abcdef1234567890",
    "x-served-by": "cache-abcdefg",
    "powered": "PHP/8.0.8",
    "x-yerdle-app-name": "yerdle/1.0",
    "WebDevSrc": "true",
    "X-Powered-PublicCMS": "v1.0",
    "X-VARITI-CCR": "12345abcdef",
    "X-Pass-Why": "abcdefg12345",
    "X-Content-Encoded-By": "gzip",
    "X-Flow-Powered": "Fastly",
    "x-now-trace": "abcdefg12345",
    "X-XRDS-Location": "https://example.com/xrds",
    "x-vercel-id": "abcdefg12345",
    "x-contentful-request-id": "abcdefg12345",
    "azure-version": "1.0.0",
    "x-platform-server": "nginx",
    "x-amz-rid": "abcdef1234567890",
    "x-fw-type": "akamai",
    "x-cf-ipfs-cache-status": "HIT",
    "X-ServedBy": "cache-abcdefg",
    "X-Lift-Version": "2.6.3",
    "x-rebelmouse-surrogate-control": "max-age=600",
    "x-sanity-shard": "abcdefg12345",
    "x-provided-by": "proxy.example.com",
    "X-Cache": "HIT",
    "x-trove-order-uuid": "abcdef1234567890",
    "X-Pardot-Rsp": "HIT",
    "cms-name": "TYPO3",
    "X-Firefox-Spdy": "h3-27",
    "ch-powered-by": "WordPress/5.7.2",
    "x-backend-server": "nginx/1.21.1",
    "X-Arastta": "Arastta/2.0.3",
    "x-powered-by": "PHP/7.4.10",
    "azure-sitename": "example",
    "x-render-origin-server": "example.com",
    "X-Jenkins": "Jenkins/2.289.3",
    "DNNOutputCache": "false",
    "x-platform-processor": "Intel Xeon",
    "x-oss-request-id": "abcdef1234567890",
    "X-Supplied-By": "proxy.example.com",
    "X-Ghost-Cache-Status": "HIT",
    "kbn-name": "kibana",
    "X-Varnish-Cache": "MISS",
    "X-CF1": "12345abcdefg",
    "x-ipfs-datasize": "1234567890",
    "X-Tumblr-User": "example",
    "cf-ray": "abcdef1234567890",
    "X-Compressed-By": "Brotli",
    "x-envoy-upstream-service-time": "100ms",
    "x-lagoon": "Lagoon",
    "X-Global-Transaction-ID": "abcdefg12345",
    "x-sucuri-cache:": "HIT",
    "X-Varnish": "abcdefg",
    "x-fastly-request-id": "12345abcdefg",
    "x-amz-err-code": "NoSuchKey",
    "X-Backdrop-Cache": "HIT",
    "Composed-By": "example.com",
    "content-security-policy": "default-src 'self'",
    "x-ms-correlation-request-id": "abcdefg1234567890",
    "X-Flex-Lang": "en-US",
    "x-0-status": "200 OK",
    "X-StatusPage-Version": "2.5.0",
    "x-fw-static": "AkamaiGHost",
    "X-AspNet-Version": "4.0.30319",
    "x-hostname": "webserver-123",
    "X-Inertia": "true",
    "x-redirected-by": "example.com",
    "frontastic-request-id": "12345abcdefg",
    "x-litespeed-cache": "HIT",
    "x-amz-request-id": "abcdefg1234567890",
    "X-MCF-ID": "abcdef1234567890",
    "x-cluster": "abcdefg",
    "x-jive-chrome-wrapped": "true",
    "x-amzn-waf-action": "allow",
    "x-ventryshield-cache-status": "HIT",
    "cf-cache-status": "HIT",
    "cache-provider": "Fastly",
    "x-platform-router": "aws",
    "x-auth0-requestid": "12345abcdefg",
    "X-Powered-CMS": "Joomla",
    "section-io-origin-status": "200",
    "Smug-CDN": "true",
    "tb-cache-group": "abcdefg",
    "X-AH-Environment": "prod",
    "x-amz-delete-marker": "false",
    "x-ms-gateway-requestid": "abcdefg12345",
    "x-ipfs-path": "/ipfs/Qmbcdefgh1234567890abcdefg",
    "x-ventryshield-sid": "abcdefg1234567890",
    "X-Hosting-Provider": "example Hosting",
    "x-rebelmouse-cache-control": "max-age=600",
    "X-Rack-Cache": "miss",
    "x-bubble-capacity-limit": "1000",
    "x-engine": "example Engine",
    "X-B3-Flags": "1",
    "x-oss-storage-class": "STANDARD",
    "x-amz-req-time-micros": "1234567890",
    "X-Jimdo-Instance": "abcdefg12345",
    "X-Spip-Cache": "HIT",
    "X-DataDome-CID": "abcdefg1234567890",
    "OracleCommerceCloud-Version": "19.3",
    "host-header": "example.com",
    "x-nestify-cache": "HIT",
    "x-trove-app-name": "example-app",
    "Itx-Generated-Timestamp": "1234567890"
}